{
    "data": [
        {
            "Owner": {
                "name": "David Kanel David Kanel Kanel David Kanel",
                "id": "4098623000000224013"
            },
            "Address": null,
            "Oilfield_Equipment": null,
            "Year_current_business_was_established": null,
            "MCS90": null,
            "Physical_Damage_Losses_Number": null,
            "E_mail_Address": null,
            "Vehicles": [
                {
                    "Radius": "300 Miles",
                    "$approval": {
                        "delegate": false,
                        "approve": false,
                        "reject": false,
                        "resubmit": false
                    },
                    "Category": "test",
                    "$currency_symbol": "$",
                    "Parent_Id": {
                        "name": "custom",
                        "id": "4098623000000351050"
                    },
                    "$editable": true,
                    "Loss_Payee": "fgfhgf",
                    "$process_flow": false,
                    "Year_Make_Model": "INTL",
                    "Value": "465",
                    "VIN": "6576hgjhkj",
                    "id": "4098623000000396003",
                    "$approved": true
                },
                {
                    "Radius": "300 Miles",
                    "$approval": {
                        "delegate": false,
                        "approve": false,
                        "reject": false,
                        "resubmit": false
                    },
                    "Category": "test",
                    "$currency_symbol": "$",
                    "Parent_Id": {
                        "name": "custom",
                        "id": "4098623000000351050"
                    },
                    "$editable": true,
                    "Loss_Payee": "fhfgnh",
                    "$process_flow": false,
                    "Year_Make_Model": "INTL",
                    "Value": "565",
                    "VIN": "gfjghkjhljl657",
                    "id": "4098623000000396005",
                    "$approved": true
                }
            ],
            "Effective_Date": null,
            "Attn": null,
            "$process_flow": false,
            "DOB": "1990-07-13",
            "Fire_Theft_w_CAC": null,
            "Agent_Code": "77743 (GIVESURANCE INS SVCS)",
            "Federal_Cargo_BMC_34": null,
            "id": "4098623000000351050",
            "First_Name_Two": null,
            "Specify_Commodities_Hauled": "ttest",
            "Department_Store_Merchandise": null,
            "Suffix_Two": "none",
            "$approval": {
                "delegate": false,
                "approve": false,
                "reject": false,
                "resubmit": false
            },
            "Trailer_Interchange": null,
            "ZIP_Code": null,
            "Created_Time": "2019-07-25T15:44:11+05:30",
            "BI_PD": null,
            "UM_PD": null,
            "Insured_s_Phone": null,
            "Docket_Number": null,
            "State_FT": null,
            "Suffix": "Sr",
            "Last_Name_Two": null,
            "Social_Security_Number": null,
            "Is_the_customer_currently_insured_with_Progressive": "No",
            "MC_MX_FF_Number_s": "5756867",
            "Tow": null,
            "Sand_Gravel": null,
            "Auto_Liability": null,
            "Posted_Date": null,
            "Policy_Effective_Date": "2019-07-30",
            "USDOT_associated_with_the_insured_s_business": "604145",
            "First_Name1": null,
            "Accident_Violation": null,
            "Injury": null,
            "Is_it_OK_if_I_continue": "Yes (most accurate quote)",
            "Salutation": null,
            "Current_Vehicle_Value": null,
            "listed_vehicles_or_the_load_require_a_placard": "Yes",
            "Full_Name": "custom",
            "Home_Address": "6300 BLAINE ROAD POPLAR GROVE, IL 61065",
            "Fax_Number": null,
            "Drivers1": [
                {
                    "$approval": {
                        "delegate": false,
                        "approve": false,
                        "reject": false,
                        "resubmit": false
                    },
                    "$currency_symbol": "$",
                    "DOB_Three": "1992-07-29",
                    "License_State": "Alaska",
                    "Parent_Id": {
                        "name": "custom",
                        "id": "4098623000000351050"
                    },
                    "$editable": true,
                    "Points": 10,
                    "License_Number": "57678799ghjhk",
                    "$process_flow": false,
                    "SR22": "Yes",
                    "id": "4098623000000435016",
                    "$approved": true,
                    "Name1": "test drivers",
                    "Age": "38"
                },
                {
                    "$approval": {
                        "delegate": false,
                        "approve": false,
                        "reject": false,
                        "resubmit": false
                    },
                    "$currency_symbol": "$",
                    "DOB_Three": "1990-07-24",
                    "License_State": "IN",
                    "Parent_Id": {
                        "name": "custom",
                        "id": "4098623000000351050"
                    },
                    "$editable": true,
                    "Points": 0,
                    "License_Number": "54658768",
                    "$process_flow": false,
                    "SR22": "Yes",
                    "id": "4098623000000429020",
                    "$approved": true,
                    "Name1": "abhi manyu test",
                    "Age": "29"
                }
            ],
            "Motor_Trucking_Cargo": null,
            "Structure": "Individual/Sole Proprietor",
            "City_Two": null,
            "AL_Deductible": null,
            "ZIP_Code_Two": "61065",
            "Proof_of_Prior_Insurance": null,
            "Insurance_Carrier": null,
            "UM_UIM1": null,
            "UM_UIM": null,
            "Logs_Poles_Beams_Lumber": null,
            "USDOT_Assigned_to": "POST OFFICE BOEX 7 TOOMSBORO, GA 31090",
            "Do_we_insure_all_commercial_vehicles_the_insured": null,
            "Number_of_Waivers_of_Subrogation": null,
            "Type": null,
            "Layout": {
                "name": "Standard",
                "id": "4098623000000091033"
            },
            "Mobile_Homes": null,
            "Non_Truck": null,
            "PIP": null,
            "Coverage_From": null,
            "Tag": [],
            "State_Two": "IL",
            "Comprehensive": null,
            "Downtime_Rental": null,
            "Other": null,
            "Machinery_Large_Objects": null,
            "Designate_Spouse_as_a_Named_Insured": "Yes",
            "Date_Two": null,
            "Single_Line_50": null,
            "Federal": null,
            "$currency_symbol": "$",
            "Middle_Initial": null,
            "Auto_Parts_Tires": null,
            "Medical_Payments": null,
            "Drivo_Tow_away": null,
            "Medical_Payment": null,
            "Metal_sheets_coils_rolls": null,
            "Are_trucks_garaged_principally_at_multiple_loctn": null,
            "Last_Activity_Time": "2019-07-31T09:18:41+05:30",
            "Policy_Surety_Number": null,
            "Cancellation_Date": null,
            "CA_Authority_Number": null,
            "To": null,
            "$approved": true,
            "Roadside_Assistance": null,
            "Date_Four": null,
            "Employer_Non_Owned_Auto": null,
            "Motor_Vehicles": null,
            "$editable": true,
            "City": null,
            "Involved_in_the_daily_operation_of_the_business": "yes",
            "UMPD": null,
            "Term": null,
            "US_Mail": null,
            "Bill_Plan": null,
            "Are_any_listed_vehicles_used_to_haul_steel": null,
            "MOTOR_TRUCK_CARGO": null,
            "Permanently_Attached_Equip": null,
            "State": null,
            "Company_Name": null,
            "Mailing_Address": "6300 BLAINE ROAD POPLAR GROVE, IL 61065",
            "Rental_Reimbursement": null,
            "General_Liability": null,
            "Do_you_have_a_DBA": "Yes",
            "Telephone": null,
            "Form": null,
            "Household_Goods": null,
            "Building_Materials": null,
            "Liability_Losses_Number": null,
            "Number_of_Additional_Insureds": null,
            "First_Name": null,
            "Is_the_customer_required_to_maintain_hours": null,
            "Single_Line_39": null,
            "Does_the_information_assigned_to_this_USDOT_match": "yes",
            "Phone": "6465966118",
            "Single_Line_37": null,
            "Last_Name1": null,
            "Single_Line_38": null,
            "Single_Line_35": null,
            "Single_Line_36": null,
            "Do_we_insure_all_vehicles_that_the_insured_uses": null,
            "Liability_Losses_Amount_Number": null,
            "Others": null,
            "Modified_Time": "2019-07-31T09:18:41+05:30",
            "Collision": null,
            "Does_the_insured_have_General_Liability_Insurance": null,
            "Fatal": null,
            "State_Cargo_Form_H": null,
            "Are_any_state_or_federal_filings_required": null,
            "Last_Name": "custom",
            "Single_Line_48": null,
            "Physical_Damage_Losses_Amount": null,
            "Total": null,
            "Single_Line_49": null,
            "Single_Line_46": null,
            "Single_Line_47": null,
            "Single_Line_44": null,
            "Single_Line_45": null,
            "Single_Line_42": null,
            "Single_Line_43": null,
            "Single_Line_40": null,
            "Single_Line_41": null
        }
    ]
}